# Project:
# Directory: /cmd
# Filename: /cmd/add-file.js
# Filename: /cmd/change-branch.js
# Filename: /cmd/clean-rest.js
# Filename: /cmd/clone-project.js
# Filename: /cmd/commit-code.js
# Filename: /cmd/compile-books.js
# Filename: /cmd/compile-diagrams.js
# Filename: /cmd/compile-docs.js
# Filename: /cmd/compile-umls.js
# Filename: /cmd/create-branch.js
# Filename: /cmd/create-controller.js
# Filename: /cmd/create-dbbackup.js
# Filename: /cmd/create-error.js
# Filename: /cmd/create-helper.js
# Filename: /cmd/create-middleware.js
# Filename: /cmd/create-template.js
# Filename: /cmd/create-vue.js
# Filename: /cmd/do.js
# Filename: /cmd/import-file.js
# Filename: /cmd/import-url.js
# Filename: /cmd/print-tree.js
# Filename: /cmd/pull-code.js
# Filename: /cmd/push-code.js
# Filename: /cmd/remove-file.js
# Filename: /cmd/show-errors.js
# Filename: /cmd/show-logs.js
# Filename: /cmd/show-routes.js
# Filename: /cmd/show-status.js
# Filename: /cmd/show-timings.js
# Filename: /cmd/show-todos.js
# Filename: /cmd/test-e2e.js
# Filename: /cmd/test-unit.js
# Filename: /cmd/update-docs.js
# Filename: /cmd/update-i18n.js
# Directory: /cmd/update-rest
# Filename: /cmd/update-rest/BaseController.js.ejs
# Filename: /cmd/update-rest/BaseModel.js.ejs
# Filename: /cmd/update-rest/cached.json
# Filename: /cmd/update-rest/Controller.js.ejs
# Filename: /cmd/update-rest/controllers.ejs
# Filename: /cmd/update-rest/export.json
# Filename: /cmd/update-rest/Model.js.ejs
# Filename: /cmd/update-rest/models.ejs
# Filename: /cmd/update-rest/postman-collection.ejs
# Directory: /cmd/update-rest/template
# Filename: /cmd/update-rest.js
# Directory: /data
# Filename: /data/db.sql
# Filename: /dev.bat
# Filename: /dev.sh
# Filename: /do.bat
# Filename: /do.sh
# Directory: /doc
# Filename: /doc/app.expolium.postman_collection.json
# Filename: /expolium.config.js
# Directory: /log
# Filename: /log/error.log
# Filename: /log/info.log
# Filename: /package-lock.json
# Filename: /package.json
# Filename: /README.md
# Filename: /script.import-dependencies.bat
# Directory: /src
# Directory: /src/core
# Directory: /src/core/app
# Directory: /src/core/app/base
# Filename: /src/core/app/base/BaseApp.js
# Filename: /src/core/app/base/BaseRouter.js
# Filename: /src/core/app/base/RestRouter.js
# Filename: /src/core/app/base/CdnRouter.js
# Filename: /src/core/app/base/LiveRouter.js
# Filename: /src/core/app/base/ContentsRouter.js
# Filename: /src/core/app/App.js
# Filename: /src/core/app/Router.js
# Directory: /src/core/config
# Filename: /src/core/config/database-schema.extension.json
# Filename: /src/core/config/database-schema.json
# Filename: /src/core/config/metadata-dependencies.json
# Directory: /src/core/controller
# Directory: /src/core/controller/base
# Filename: /src/core/controller/base/ControllerGroup.js
# Filename: /src/core/controller/base/EjsController.js
# Filename: /src/core/controller/base/EjsPageController.js
# Filename: /src/core/controller/base/Html404Controller.js
# Filename: /src/core/controller/base/JsFileController.js
# Filename: /src/core/controller/base/Json404Controller.js
# Filename: /src/core/controller/base/JsonFileController.js
# Filename: /src/core/controller/base/JsonFileIoController.js
# Filename: /src/core/controller/base/JsonFileIoMasterController.js
# Filename: /src/core/controller/base/ModelController.js
# Filename: /src/core/controller/base/RestController.js
# Filename: /src/core/controller/base/StaticController.js
# Filename: /src/core/controller/base/StaticEjsController.js
# Filename: /src/core/controller/base/Controller.js
# Directory: /src/core/controller/backoffice
# Filename: /src/core/controller/backoffice/BackOfficeController.js
# Directory: /src/core/controller/auth
# Filename: /src/core/controller/auth/LoginController.js
# Filename: /src/core/controller/auth/LoginPageController.js
# Filename: /src/core/controller/auth/LogoutController.js
# Filename: /src/core/controller/auth/RecoverController.js
# Filename: /src/core/controller/auth/RegisterController.js
# Filename: /src/core/controller/auth/UnregisterController.js
# Directory: /src/core/controller/rest
# Directory: /src/core/controller/rest/base
# Filename: /src/core/controller/rest/base/BaseCommunityController.js
# Filename: /src/core/controller/rest/base/BaseEjemplosController.js
# Filename: /src/core/controller/rest/base/BaseMembershipController.js
# Filename: /src/core/controller/rest/base/BasePermissionController.js
# Filename: /src/core/controller/rest/base/BasePermissionPerRoleController.js
# Filename: /src/core/controller/rest/base/BaseRoleController.js
# Filename: /src/core/controller/rest/base/BaseSessionController.js
# Filename: /src/core/controller/rest/base/BaseUserController.js
# Filename: /src/core/controller/rest/CommunityController.js
# Filename: /src/core/controller/rest/EjemplosController.js
# Filename: /src/core/controller/rest/MembershipController.js
# Filename: /src/core/controller/rest/PermissionController.js
# Filename: /src/core/controller/rest/PermissionPerRoleController.js
# Filename: /src/core/controller/rest/RoleController.js
# Filename: /src/core/controller/rest/SessionController.js
# Filename: /src/core/controller/rest/UserController.js
# Filename: /src/core/controller/controllers.js
# Directory: /src/core/database
# Filename: /src/core/database/db.js
# Filename: /src/core/database/db2.js
# Filename: /src/core/database/db3.js
# Directory: /src/core/error
# Directory: /src/core/error/base
# Filename: /src/core/error/base/BaseError.js
# Filename: /src/core/error/ErrorManager.js
# Directory: /src/core/helper
# Directory: /src/core/helper/base
# Filename: /src/core/helper/base/Tools.js
# Filename: /src/core/helper/base/BaseHelper.js
# Filename: /src/core/helper/AuthenticationManager.js
# Filename: /src/core/helper/CheckManager.js
# Filename: /src/core/helper/CliUtils.js
# Filename: /src/core/helper/CollectionManager.js
# Filename: /src/core/helper/DBManager.js
# Filename: /src/core/helper/dd.js
# Filename: /src/core/helper/ImportManager.js
# Filename: /src/core/helper/LoggerManager.js
# Filename: /src/core/helper/ModelManager.js
# Filename: /src/core/helper/ParametersManager.js
# Filename: /src/core/helper/ReflectionManager.js
# Filename: /src/core/helper/ResponseManager.js
# Filename: /src/core/helper/StoreManager.js
# Filename: /src/core/helper/StringUtils.js
# Filename: /src/core/helper/TemplateManager.js
# Directory: /src/core/middleware
# Directory: /src/core/middleware/base
# Filename: /src/core/middleware/base/BaseMiddleware.js
# Filename: /src/core/middleware/AuthMiddleware.js
# Directory: /src/core/model
# Directory: /src/core/model/base
# Filename: /src/core/model/base/BaseCommunity.js
# Filename: /src/core/model/base/BaseEjemplos.js
# Filename: /src/core/model/base/BaseMembership.js
# Filename: /src/core/model/base/BasePermission.js
# Filename: /src/core/model/base/BasePermissionPerRole.js
# Filename: /src/core/model/base/BaseRole.js
# Filename: /src/core/model/base/BaseSession.js
# Filename: /src/core/model/base/BaseUser.js
# Filename: /src/core/model/Community.js
# Filename: /src/core/model/Ejemplos.js
# Filename: /src/core/model/Membership.js
# Filename: /src/core/model/models.js
# Filename: /src/core/model/Permission.js
# Filename: /src/core/model/PermissionPerRole.js
# Filename: /src/core/model/Role.js
# Filename: /src/core/model/Session.js
# Filename: /src/core/model/User.js
# Directory: /src/core/project
# Directory: /src/core/project/base
# Filename: /src/core/project/base/BaseProject.js
# Filename: /src/core/project/Project.js
# Directory: /src/core/public
# Directory: /src/core/public/rendered
# Filename: /src/core/public/rendered/home.ejs
# Directory: /src/core/public/static
# Directory: /src/core/public/static/assets
# Directory: /src/core/public/static/assets/img
# Directory: /src/core/public/static/assets/lib
# Filename: /src/core/public/static/assets/lib/bootstrap.css
# Filename: /src/core/public/static/assets/lib/bootstrap.js
# Filename: /src/core/public/static/assets/lib/custom.rest.css
# Filename: /src/core/public/static/assets/lib/global.1.js
# Filename: /src/core/public/static/assets/lib/jquery.js
# Filename: /src/core/public/static/assets/lib/popper.js
# Directory: /src/core/query
# Directory: /src/core/query/base
# Directory: /src/core/query/base/BaseQuery.js
# Filename: /src/core/query/InsertSessionByUserId.js
# Filename: /src/core/query/SelectUserByNameOrEmail.js
# Directory: /src/core/store
# Directory: /src/core/store/base
# Filename: /src/core/store/base/BaseStore.js
# Filename: /src/core/store/JsonFileStore.js
# Filename: /src/core/store/RawFileStore.js
# Filename: /src/core/store/TextFileStore.js
# Directory: /src/core/template
# Directory: /src/core/template/html
# Directory: /src/core/template/html/error
# Filename: /src/core/template/html/error/404.ejs
# Directory: /src/core/template/html/auth
# Filename: /src/core/template/html/auth/login.ejs
# Filename: /src/core/template/html/auth/logout.ejs
# Filename: /src/core/template/html/auth/register.ejs
# Filename: /src/core/template/html/auth/remind.ejs
# Directory: /src/core/template/html/page
# Filename: /src/core/template/html/page/home.ejs
# Directory: /src/core/template/html/partial
# Filename: /src/core/template/html/partial/footer.ejs
# Filename: /src/core/template/html/partial/header.ejs
# Filename: /src/core/template/html/partial/menu.ejs
# Directory: /src/core/template/html/menu
# Filename: /src/core/template/html/menu/nav.ejs
# Directory: /src/core/template/html/rest
# Filename: /src/core/template/html/rest/overview.ejs
# Filename: /src/core/template/html/rest/view-many.ejs
# Filename: /src/core/template/html/rest/view-one.ejs
# Filename: /src/env.js
# Filename: /src/load.js
# Filename: /src/start.js
# Directory: /test
# Directory: /test/e2e
# Directory: /test/unit
